### ISSUE TITLE
doesn't working with the cities skyline 2

### ISSUE THREAD

**Issue by Andy981008ISmyPass** [oureveryday/Steam-API-Check-Bypass#2]
so sad, i just tried method 1 then it is still not working tho :(

**Comment by oureveryday** [comment]
can u sure the game really checking steam api dll?

**Comment by Andy981008ISmyPass** [comment]
> can u sure the game really checking steam api dll?

i am not sure :(

**Comment by Andy981008ISmyPass** [comment]
試了還是不行，不明白

**Comment by Andy981008ISmyPass** [comment]
同志，就靠你了 我試了第一個方法還是會閃退

**Comment by oureveryday** [comment]
cs.rin.ru没现成的破解吗？

**Comment by Andy981008ISmyPass** [comment]
等等，沒事了，我用你甚麼goldberg修改器修好了，感謝你
